export const Actions = {
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  VERIFY: "VERIFY",
  GETYEARLYQUESTIONS: "GETYEARLYQUESTIONS",
  WRITETHEEXAM: "WRITETHEEXAM",
  SUBMITEXAM: "SUBMITEXAM",
  ENDTHEEXAM: "ENDTHEEXAM",
  PREMIUMEXAMS: "PREMIUMEXAMS",
  MOCKEXAMS: "MOCKEXAMS",
};
